python train.py teen \
    -project teen \
    -dataset cifar100 \
    -dataroot CIFAR_DATA_DIR \
    -base_mode 'ft_cos' \
    -new_mode 'avg_cos' \
    -lr_base 0.1 \
    -decay 0.0005 \
    -epochs_base 600 \
    -batch_size_base 256 \
    -schedule Cosine \
    -tmax 600 \
    -gpu '2' \
    -temperature 16 \
    -softmax_t 16 \
    -shift_weight 0.1
